### ISSUE TITLE
Get the current version

### ISSUE THREAD

**Issue by John-Gee** [zom-ponks/rpcs3-gameupdater#13]
Unless I am wrong, we don't check for what version we currently have, so we'd always be downloading the updates.

I'm not yet sure how to do that.

**Comment by John-Gee** [comment]
Maybe this is helpful: https://www.psdevwiki.com/ps3/PKG_files#Example_from_a_finalized_PS3_.pkg

make_package_npdrm Revision (2 bytes) + Package Version (2 bytes) or unk (1 byte) + PS3/PSP/PSP2 System Version (3 bytes) + Package Version (2 bytes) + App Version (2 bytes)

I found that link in here: https://github.com/Megamouse/rpcs3/blob/targetter/rpcs3/Crypto/unpkg.h

**Comment by zom-ponks** [comment]
RPCS3 doesn't seem to cache this information anywhere.

**Comment by John-Gee** [comment]
Well if RPCS3 does not give it to us, we'll have to get it ourselves then.

Wasn't there anything like that in the vb?

**Comment by John-Gee** [comment]
Alright it is in param.sfo's in the game's folder.
I thought this was a text file but it's actually a binary one, it's at the end.

**Comment by John-Gee** [comment]
Initial code for this in PR#15
