### ISSUE TITLE
Need to handle multiple appearance of the same game

### ISSUE THREAD

**Issue by John-Gee** [zom-ponks/rpcs3-gameupdater#16]
We could have the same game in different locations, we need to understand it is the same, and handle this appropriately.

(some games install some data, or maybe it is an update, etc)

Right now we just grab them all, which means we have dupes, we may also grab an update for a game that already has it installed because we don't see the link.

**Comment by zom-ponks** [comment]
How does RPCS3 handle duplicates?

**Comment by John-Gee** [comment]
Oh that's not what I meant.

I think you can have the base game in /disc then some game data in /game and probably updates there too. Not sure what goes in dev_hdd1.  If all those have the same gameID they are duplicates but right now the script would grab them all.

This needs to be verified, I guess I'll do that later. If it's correct then we'll have to clean up the logic.

**Comment by zom-ponks** [comment]
When adding to the games list when scanning, we could check for existence of game ID and only add if it doesn't exist.

This would lead to "first come, first served" behavior, and I don't think it would be trivial to have any options for the user to choose which one. But if the game ID is the same, then the updates would be the same.

**Comment by John-Gee** [comment]
Well I don't know if that will always work, but it's definitely something we can look at.

**Comment by John-Gee** [comment]
Should be taken care of by #28
